#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail

# [Workflow:]
#
# - Your feature branch must be rebased on main prior
# - "ff-only" will reject the merge if not
# - `git merge -ff-only --squash <feature_branch>`
# - Index has staged, but uncommitted changes
# - To summarize them, you then run:
# - `git summary`
# - It will output a summary that you can then use to write your commit message

summary='.git/summary'

rm -f "$summary"

touch "$summary"

echo '<SCOPE>: <TITLE>' >>"$summary"
echo >>"$summary"

echo '-----' >>"$summary"
echo 'STAT:' >>"$summary"
echo '-----' >>"$summary"

echo >>"$summary"
git diff --staged --shortstat >>"$summary"
echo >>"$summary"

echo '--------' >>"$summary"
echo 'CHANGES:' >>"$summary"
echo '--------' >>"$summary"

echo >>"$summary"
git diff --staged --stat >>"$summary"
echo >>"$summary"

echo '--------' >>"$summary"
echo 'TESTING:' >>"$summary"
echo '--------' >>"$summary"

echo >>"$summary"
echo 'TODO...' >>"$summary"
echo >>"$summary"

echo '----------' >>"$summary"
echo 'CI CHECKS:' >>"$summary"
echo '----------' >>"$summary"

echo >>"$summary"
echo 'TODO...' >>"$summary"

echo "$summary"
echo '----------------'
cat "$summary"
